Add Quickstart Examples
gemfire/gemfire-examples pull request #29
Opened 2023-03-01 19:05 UTC by vfordpivotal

* Adds 3 examples with additional documentation
* Basic put/get example
* User defined classes and PDX
* Using new GF 10+ JSON document

2023-03-01 22:27 UTC, charliemblack approved these changes
Ship it

2023-03-02 18:17 UTC, davebarnes97 commented on quickstart/001_client_server_introduction/README.md
> +Download and install VMware GemFire from [Tanzu Network](https://network.pivotal.io). Follow the installation instructions in the [GemFire documentation](https://docs.vmware.com/en/VMware-Tanzu-GemFi
"VMware-Tanzu-GemFire/index.html" -> "VMware-GemFire/index.html"

2023-03-02 18:19 UTC, davebarnes97 commented on quickstart/001_client_server_introduction/README.md
> +Set Gemfire home environment variable to top of GemFire install directory. Note for this example Gemfire is installed in the home directory of the user - adjust as necessary for local environment and
"Set Gemfire home environment variable to top..." -> "Set the GEMFIRE_HOME environment variable to the top..."

2023-03-02 18:22 UTC, davebarnes97 commented on quickstart/001_client_server_introduction/README.md
> +the *help* command will list them and the gfsh interactive shell has tab completion to help with determining options for each command. For additional information checkout the [GFSH documation](https:
"https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-tools_modules-gfsh-chapter_overview.html" -> "https://docs.vmware.com/en/VMware-GemFire/9.15/gf/tools_modules-gfsh-chapter_overview.html"

2023-03-02 18:22 UTC, davebarnes97 commented on quickstart/001_client_server_introduction/README.md
> +A [Region](https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-developing-region_options-chapter_overview.html) is the core structure in the server for holding and managing key-value data i
"https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-developing-region_options-chapter_overview.html" -> "https://docs.vmware.com/en/VMware-GemFire/9.15/gf/developing-region_options-chapter_overview.html"

2023-03-02 18:23 UTC, davebarnes97 commented on quickstart/001_client_server_introduction/README.md
> +While still in the gfsh interactive shell, create a [partition region](https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-developing-partitioned_regions-chapter_overview.html).
"https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-developing-partitioned_regions-chapter_overview.html" -> "https://docs.vmware.com/en/VMware-GemFire/9.15/gf/developing-partitioned_regions-chapter_overview.html"

2023-03-02 18:29 UTC, davebarnes97 requested changes
@vfordpivotal Nice work - docs and examples, both.
I plan to run these myself and provide feedback, but due to schedules I may not be able to start for a week or more. So if you'd like, you can merge these without waiting for me. I'll run them later and submit tickets if I find issues.
Before you merge, please update the doc URLs. They changed out from under you while you were developing these examples. The new pattern has 3 differences from the old one:

- "VMware-Tanzu-GemFire" is now "VMware-GemFire"
- "tgf" is now "gf"
- the "GUID-" string (a DocWorks artifact) is gone
So, for example:
"https://docs.vmware.com/en/VMware-Tanzu-GemFire/9.15/tgf/GUID-developing-region_options-chapter_overview.html" -> "https://docs.vmware.com/en/VMware-GemFire/9.15/gf/developing-region_options-chapter_overview.html"
There are a few more subtleties when it comes to the GF-for-TAS (GF-for-VMs) doc -- LMK if you'd like the complete mapping for the entire doc set.

2023-03-03 21:47 UTC, metatype approved these changes

2023-03-03 21:50 UTC, merged